# Generated by Django 3.0 on 2021-01-07 10:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210106_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('degree', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('career', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('topCol', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('admsnProcess', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('admsnGuid', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=180)),
            ],
        ),
    ]
